version: 1
formatters:
  brief:
    format: '%(message)s'
  with_timestamp:
    format: '[%(asctime)s] [%(module)-10s] %(levelname)-8s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO # DEBUG
    formatter: brief # with_timestamp
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: with_timestamp
    filename: driver_alert_debug.log
    maxBytes: 1073741824   # 1G
    backupCount: 3
loggers:
  driver_alert:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  handlers: [console]
